# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_pb2 as main__pb2


class ChatterStub(object):
    """The chat service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateDatabase = channel.unary_unary(
                '/Chatter/UpdateDatabase',
                request_serializer=main__pb2.UpdateRequest.SerializeToString,
                response_deserializer=main__pb2.UpdateResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/Chatter/Heartbeat',
                request_serializer=main__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=main__pb2.HeartbeatResponse.FromString,
                )


class ChatterServicer(object):
    """The chat service definition.
    """

    def UpdateDatabase(self, request, context):
        """Starts a chat with the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Sends heartbeat check to other servers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDatabase,
                    request_deserializer=main__pb2.UpdateRequest.FromString,
                    response_serializer=main__pb2.UpdateResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=main__pb2.HeartbeatRequest.FromString,
                    response_serializer=main__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Chatter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chatter(object):
    """The chat service definition.
    """

    @staticmethod
    def UpdateDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chatter/UpdateDatabase',
            main__pb2.UpdateRequest.SerializeToString,
            main__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chatter/Heartbeat',
            main__pb2.HeartbeatRequest.SerializeToString,
            main__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
